### ISSUE TITLE
Assembly is not signed

### ISSUE THREAD

**Issue by scsaba** [serilog-contrib/Serilog.Enrichers.Sensitive#12]
Please provide the signed version of the Serilog.Enrichers.Sensitive library in the nuget package.

Is it intentional that you added the debug build and not release?

**Comment by sandermvanvliet** [comment]
@scsaba if you need a signed version consider funding the work by sponsoring this project.

**Comment by scsaba** [comment]
Signing the assembly is good for you, not me. Anybody can sign an unsigned assembly...
