### ISSUE TITLE
Why does Nuget show 1.2.0 as latest release, although here 1.1.0 is the latest release?

### ISSUE THREAD

**Issue by mbs-janbe** [serilog-contrib/Serilog.Enrichers.Sensitive#14]
This site lists 1.1.0 as latest release:
https://github.com/serilog-contrib/Serilog.Enrichers.Sensitive/releases

Nuget lists 1.2.0 as highest release version, released 1 day after 1.1.0:
https://www.nuget.org/packages/Serilog.Enrichers.Sensitive/1.2.0#versions-body-tab

**Comment by sandermvanvliet** [comment]
Because currently the releases aren’t automatically created when a release build kicks off.

that will happen when the github actions start working properly
