### ISSUE TITLE
Transform C# Configuration as Json

### ISSUE THREAD

**Issue by SViradiya-MarutiTech** [serilog-contrib/Serilog.Enrichers.Sensitive#20]
We are not doing hard code C# hard code configuration in Startup/Program.cs, we have stored JSON Configuration of Serilog in AWS SSM, So to apply this Enrichers, how can I transform or configure below code  in JSON?

```c#
  var logger = new LoggerConfiguration()
                .Enrich.WithSensitiveDataMasking(o =>
                {
                    o.Mode = MaskingMode.Globally;
                    o.ExcludeProperties.Add("email");
                    o.MaskValue = "^^";
                })
                .WriteTo.Console()
                .CreateLogger();

```

I able to Set Enricher in Serilog JSON Configuration like below. I am using other Enrichers as JSON configuration only.

```json
"Serilog": {
    "Enrich": {
        "WithSensitiveDataMasking": {
            "Name": "WithSensitiveDataMasking"
        }
    }
}
```

but not able to transform other proprties.

**Comment by SViradiya-MarutiTech** [comment]
I tried below, but no luck

```json
{
  "Serilog": {
    "Enrich": {
      "WithSensitiveDataMasking": {
        "Name": "WithSensitiveDataMasking",
        "Args": {
          "SensitiveDataEnricherOptions": {
            "Mode": "Globally",
            "ExcludeProperties": [
              "email"
            ],
            "MaskValue": "^^"
          }
        }
      }
    }
  }
}
```

**Comment by sandermvanvliet** [comment]
Because configuration of the enricher uses an `options` lambda it's not possible to use the currently supported configuration for the enricher via JSON as you can't "serialize" something like: `options => options.MaskValue = "CUSTOM";` to JSON.

**Comment by sandermvanvliet** [comment]
Turned out to be not super hard: https://github.com/serilog-contrib/Serilog.Enrichers.Sensitive#json-configuration

Will be in package release 1.7.0 which should appear on NuGet shortly.

**Comment by SViradiya-MarutiTech** [comment]
@sandermvanvliet  Thanks a lot..

**Comment by SViradiya-MarutiTech** [comment]
Can we add Custom masking operators, as in latest release, you have provided Custom masking on Email. but I am thinking to add in MakingOperators list, So is it possible?

```json

{
  "Serilog": {
    "Using": [
      "Serilog.Enrichers.Sensitive"
    ],
    "Enrich": [
      {
        "Name": "WithSensitiveDataMasking",
        "Args": {
          "options": {
            "MaskValue": "CUSTOM_MASK_FROM_JSON",
            "ExcludeProperties": [
              "email"
            ],
            "MaskingOperators":["My.Assembly.Name.CustomMaskingOperator"],

            "Mode": "Globally"
          }
        }
      }
    ]
  }
}
```
