### ISSUE TITLE
How to add custom MaskingOperators from appsetings.json?

### ISSUE THREAD

**Issue by alexandries98** [serilog-contrib/Serilog.Enrichers.Sensitive#24]
Hello,

I made a custom masking operator that is working via code configuration, but for some reason it can not be seen from the appsettings.json.

This is the custom masking operator.
```C#
namespace SerilogPOC.API.LoggingMasks
{
    public class CustomSecretMaskingOperator : RegexMaskingOperator
    {
        public CustomSecretMaskingOperator() 
            : base("[a-z]*#[a-z]*")
        {
        }

        protected override string PreprocessMask(string mask, Match match)
        {
            var tokens = match.Value.Split("#");

            return tokens[0] + "#" + mask; 
        }
    }
}
```

This is how I am using it in code and it works as expected.

```C#
.UseSerilog((context, services, cfg) => cfg
            .ReadFrom.Configuration(configuration)
            .Enrich.WithSensitiveDataMasking(operations =>
            {
                operations.MaskingOperators.Add(new CustomSecretMaskingOperator());
                operations.MaskValue = "**SECRET**";
            }));
```

But, when it comes to use it from the appsetings, things just don't work and I don't know what I am doing wrong.

```C#
.UseSerilog((context, services, cfg) => cfg
            .ReadFrom.Configuration(configuration));
```

```JSON
{
  "Serilog": {
    "Using": [
      "Serilog.Sinks.Console",
      "Serilog.Sinks.File",
      "Serilog.Enrichers.Environment",
      "Serilog.Enrichers.Sensitive",
      "API"
    ],
    "WriteTo": [
      { "Name": "Console" },
      {
        "Name": "File",
        "Args": {
          "path": "log.txt",
          "outputTemplate": "[{MachineName}] {Timestamp:yyyy-MM-dd HH:mm:ss} [{Level:u3}] {Message:lj}\n",
          "rollingInterval": "Day",
          "rollOnFileSizeLimit": true,
          "fileSizeLimitBytes": 20480,
          "retainedFileCountLimit": 10
        }
      }
    ],
    "Enrich": [
      { "Name": "WithMachineName" },
      {
        "Name": "WithSensitiveDataMasking",
        "Args": {
          "options": {
            "MaskValue": "**SECRET**",
            "MaskingOperators": [ "CustomSecretMaskingOperator" ]
          }
        }
      }
    ]
  }
}
```

The assembly name where my custom masking operator is defined is ```API``` and I am including it in ```Using```.
Am I doing things wrong in ```MaskingOperators``` or in any other part, or it is simply not possible to achieve this behavior?

Thank you!

**Comment by sandermvanvliet** [comment]
Currently this is not supported because the Serilog configuration library doesn’t know how to deal with an array of instances. Or, at least not in this form. 

I’ve started some investigation as this topic has come up three times by three different people in the last two weeks 😅

**Comment by alexandries98** [comment]
Oh, alright! Many thanks. Have a great day! 😄

**Comment by sandermvanvliet** [comment]
Release [1.7.1](https://github.com/serilog-contrib/Serilog.Enrichers.Sensitive/releases/tag/1.7.1.0) now supports this. Have a look at the README on how to configure.
