### ISSUE TITLE
FromLogContext property with destructured object are not masked

### ISSUE THREAD

**Issue by geminixandroid** [serilog-contrib/Serilog.Enrichers.Sensitive#30]
```
using var logContext = LogContext.PushProperty("Message", someObject, true);
logger.LogInformation("some text")
```
How to mask someObject property?

**Comment by geminixandroid** [comment]
`using var logContext = LogContext.PushProperty("Message", someObject, true);

 logger.LogInformation("some text")`

**Comment by sandermvanvliet** [comment]
I've created a reproduction test case for this and the problem is with the order in which enrichers are configured on the logger.
In order for log context properties to be masked correctly, the sensitive data masking enricher _must_ be added last.

**This will work:**

```csharp
var logger = new LoggerConfiguration()
   .Enrich.FromLogContext()
   .Enrich.WithSensitiveDataMasking()
   .CreateLogger();

LogContext.PushProperty("Prop", "test@example.com");

logger.Information("Hello, world!");

// Prop will be ***MASKED***
```

**This will NOT work:**

```csharp
var logger = new LoggerConfiguration()
   .Enrich.WithSensitiveDataMasking()
   .Enrich.FromLogContext()
   .CreateLogger();

LogContext.PushProperty("Prop", "test@example.com");

logger.Information("Hello, world!");

// Prop will be test@example.com
```

Unfortunately right now there isn't much I can do about that.

**Comment by geminixandroid** [comment]
@sandermvanvliet, thank you very much :)

**Comment by sandermvanvliet** [comment]
Alternatively, I would recommend this approach if possible:

```csharp
var logger = Log.Logger.ForContext("myprop", "myval");

logger.Information("Hello, world!");
```

in this case the property is always masked if you add that property to the masking configuration.
