### ISSUE TITLE
Load confirmation from serilog-settings-appsettings

### ISSUE THREAD

**Issue by ngchungsi** [serilog-contrib/Serilog.Enrichers.Sensitive#33]
Hi,

I’m having issues setting the configuration using serilog-settings-appsettings using <appsettings>.

Setting any parameters mode, mask, exclude property, etc are not set when assigned in <appsettings> in the app.config or web.config.

Is it possible to provide samples on setting these parameters.

**Comment by sandermvanvliet** [comment]
I’ve never used that library before but perhaps the JSON configuration demonstrated [here](https://github.com/serilog-contrib/Serilog.Enrichers.Sensitive#json-configuration) might give you some hints

**Comment by ngchungsi** [comment]
Hi,Thanks for the reply, I will raise an issue with against that addin as they should manage complex types.Using appsetting.json works however the app is using the web.configSent from my iPhoneOn 14/10/2023, at 8:56 PM, Sander van Vliet ***@***.***> wrote:﻿
I’ve never used that library before but perhaps the JSON configuration demonstrated here might give you some hints
